GLPI 9.3 compatibility
pluginsGLPI/prelude pull request #10
Opened 2018-08-20 14:29 UTC by cedric-anne

2018-08-20 14:29 UTC, cedric-anne commented
Includes amended https://github.com/pluginsGLPI/prelude/pull/8.

2018-08-21 06:24 UTC, orthagh requested changes

2018-08-21 06:24 UTC, orthagh commented on inc/ticket.class.php
> +      return Html::scriptBlock("
return ? it mut be an `echo`

2018-08-21 07:44 UTC, cedric-anne commented on inc/ticket.class.php
> +      return Html::scriptBlock("
Fixed.

2018-08-21 09:31 UTC, orthagh approved these changes

2018-08-21 09:32 UTC, merged